nodeLinker: pnp
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
packageExtensions:
  "@lavaclient/queue@*":
    dependencies:
      "@lavaclient/types": "*"
      "tiny-typed-emitter": "*"
